spring.mvc.view:
  prefix: '/WEB-INF/view/'
  suffix: '.jsp'

shop:
  properties:
    products:
      - product:
        id: 1
        name: 'Phone1'
        price: 50.0
      - product:
        id: 2
        name: 'Phone2'
        price: 50.0
      - product:
        id: 3
        name: 'Phone2'
        price: 50.0